"""add_api_message_id_field

Revision ID: 0b30f7c5b26a
Revises: 3f4e2a601607
Create Date: 2025-11-16 17:54:36.482698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b30f7c5b26a'
down_revision: Union[str, None] = '3f4e2a601607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_states_direction'), table_name='sync_states')
    op.drop_table('sync_states')
    op.alter_column('channel_analytics', 'channel_id',
               existing_type=sa.UUID(),
               comment='Foreign key to channel',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'date',
               existing_type=sa.DATE(),
               comment='Date of the analytics record',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Total number of messages',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'match_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Total number of matched messages',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'top_symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Top 10 symbols mentioned: [{'id': 1, 'word': 'فولاد', 'count': 15}, ...]",
               existing_comment='Top 10 symbols mentioned',
               existing_nullable=True)
    op.alter_column('channel_analytics', 'top_industries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Top 10 industries mentioned: [{'id': 1, 'name': 'فلزات', 'count': 25}, ...]",
               existing_comment='Top 10 industries mentioned',
               existing_nullable=True)
    op.alter_column('channel_analytics', 'top_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="Top 10 dictionary categories: [{'id': 1, 'name': 'نمادها', 'count': 50}, ...]",
               existing_comment='Top 10 dictionary categories',
               existing_nullable=True)
    op.create_index(op.f('ix_channel_analytics_id'), 'channel_analytics', ['id'], unique=False)
    # Skip creating uq_message_tag - it already exists
    # op.create_unique_constraint('uq_message_tag', 'message_tags', ['message_id', 'tag_id'])
    op.add_column('messages', sa.Column('api_message_id', sa.BigInteger(), nullable=True, comment='API database message ID'))
    op.alter_column('messages', 'telegram_message_id',
               existing_type=sa.BIGINT(),
               comment='Original Telegram message ID from channel',
               existing_comment='Original Telegram message ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'telegram_message_id',
               existing_type=sa.BIGINT(),
               comment='Original Telegram message ID',
               existing_comment='Original Telegram message ID from channel',
               existing_nullable=False)
    op.drop_column('messages', 'api_message_id')
    # Skip dropping uq_message_tag - we didn't create it
    # op.drop_constraint('uq_message_tag', 'message_tags', type_='unique')
    op.drop_index(op.f('ix_channel_analytics_id'), table_name='channel_analytics')
    op.alter_column('channel_analytics', 'top_categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Top 10 dictionary categories',
               existing_comment="Top 10 dictionary categories: [{'id': 1, 'name': 'نمادها', 'count': 50}, ...]",
               existing_nullable=True)
    op.alter_column('channel_analytics', 'top_industries',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Top 10 industries mentioned',
               existing_comment="Top 10 industries mentioned: [{'id': 1, 'name': 'فلزات', 'count': 25}, ...]",
               existing_nullable=True)
    op.alter_column('channel_analytics', 'top_symbols',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Top 10 symbols mentioned',
               existing_comment="Top 10 symbols mentioned: [{'id': 1, 'word': 'فولاد', 'count': 15}, ...]",
               existing_nullable=True)
    op.alter_column('channel_analytics', 'match_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Total number of matched messages',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'message_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Total number of messages',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of the analytics record',
               existing_nullable=False)
    op.alter_column('channel_analytics', 'channel_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Foreign key to channel',
               existing_nullable=False)
    op.create_table('sync_states',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('current_offset', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_available', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages_synced', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_running', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sync_states_pkey'))
    )
    op.create_index(op.f('ix_sync_states_direction'), 'sync_states', ['direction'], unique=False)
    # ### end Alembic commands ###
