"""create_sync_states_table_if_not_exists

Revision ID: e75add1f7c96
Revises: 129d6cc04084
Create Date: 2025-11-16 18:28:45.084836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e75add1f7c96'
down_revision: Union[str, None] = '129d6cc04084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('current_offset', sa.Integer(), nullable=False),
    sa.Column('total_available', sa.Integer(), nullable=True),
    sa.Column('messages_synced', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_states_direction'), 'sync_states', ['direction'], unique=False)
    # Skip creating uq_message_tag - it already exists
    # op.create_unique_constraint('uq_message_tag', 'message_tags', ['message_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping uq_message_tag - we didn't create it
    # op.drop_constraint('uq_message_tag', 'message_tags', type_='unique')
    op.drop_index(op.f('ix_sync_states_direction'), table_name='sync_states')
    op.drop_table('sync_states')
    # ### end Alembic commands ###
