"""Add dictionary system models

Revision ID: 2e171cde7221
Revises: 968a0154d887
Create Date: 2025-11-15 14:59:26.791711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e171cde7221'
down_revision: Union[str, None] = '968a0154d887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionaries',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Dictionary name (e.g., لغت\u200cنامه سیاسی)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Dictionary description'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether dictionary is active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionaries_id'), 'dictionaries', ['id'], unique=False)
    op.create_index(op.f('ix_dictionaries_name'), 'dictionaries', ['name'], unique=True)
    op.create_table('dictionary_categories',
    sa.Column('dictionary_id', sa.UUID(), nullable=False, comment='Foreign key to dictionary'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Category name (e.g., مثبت، منفی، نماد)'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Foreign key to parent category'),
    sa.Column('description', sa.Text(), nullable=True, comment='Category description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dictionary_id'], ['dictionaries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['dictionary_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_categories_dictionary_id'), 'dictionary_categories', ['dictionary_id'], unique=False)
    op.create_index(op.f('ix_dictionary_categories_id'), 'dictionary_categories', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_categories_name'), 'dictionary_categories', ['name'], unique=False)
    op.create_index(op.f('ix_dictionary_categories_parent_id'), 'dictionary_categories', ['parent_id'], unique=False)
    op.create_table('dictionary_words',
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Foreign key to dictionary category'),
    sa.Column('word', sa.String(length=255), nullable=False, comment='Original word (e.g., خودروسازی، توافق)'),
    sa.Column('normalized_word', sa.String(length=255), nullable=False, comment='Normalized word for matching (e.g., خودروساز, توافق)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether word is active for matching'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['dictionary_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_word', 'dictionary_words', ['category_id', 'normalized_word'], unique=False)
    op.create_index('idx_word_active', 'dictionary_words', ['normalized_word', 'is_active'], unique=False)
    op.create_index(op.f('ix_dictionary_words_category_id'), 'dictionary_words', ['category_id'], unique=False)
    op.create_index(op.f('ix_dictionary_words_id'), 'dictionary_words', ['id'], unique=False)
    op.create_index(op.f('ix_dictionary_words_normalized_word'), 'dictionary_words', ['normalized_word'], unique=False)
    op.create_index(op.f('ix_dictionary_words_word'), 'dictionary_words', ['word'], unique=False)
    op.create_table('message_dictionaries',
    sa.Column('message_id', sa.UUID(), nullable=False, comment='Foreign key to message'),
    sa.Column('word_id', sa.UUID(), nullable=False, comment='Foreign key to dictionary word'),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the match was made'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['dictionary_words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'word_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_dictionaries')
    op.drop_index(op.f('ix_dictionary_words_word'), table_name='dictionary_words')
    op.drop_index(op.f('ix_dictionary_words_normalized_word'), table_name='dictionary_words')
    op.drop_index(op.f('ix_dictionary_words_id'), table_name='dictionary_words')
    op.drop_index(op.f('ix_dictionary_words_category_id'), table_name='dictionary_words')
    op.drop_index('idx_word_active', table_name='dictionary_words')
    op.drop_index('idx_category_word', table_name='dictionary_words')
    op.drop_table('dictionary_words')
    op.drop_index(op.f('ix_dictionary_categories_parent_id'), table_name='dictionary_categories')
    op.drop_index(op.f('ix_dictionary_categories_name'), table_name='dictionary_categories')
    op.drop_index(op.f('ix_dictionary_categories_id'), table_name='dictionary_categories')
    op.drop_index(op.f('ix_dictionary_categories_dictionary_id'), table_name='dictionary_categories')
    op.drop_table('dictionary_categories')
    op.drop_index(op.f('ix_dictionaries_name'), table_name='dictionaries')
    op.drop_index(op.f('ix_dictionaries_id'), table_name='dictionaries')
    op.drop_table('dictionaries')
    # ### end Alembic commands ###
