"""Initial tables - categories, channels, messages, tags

Revision ID: 968a0154d887
Revises: 
Create Date: 2025-11-15 11:59:53.096924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '968a0154d887'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Category name'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Foreign key to parent category'),
    sa.Column('description', sa.Text(), nullable=True, comment='Category description'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Tag name'),
    sa.Column('tag_type', sa.Enum('CHARACTER_COUNT', 'WORD_COUNT', 'CUSTOM', name='tag_type_enum'), nullable=False, comment='Type of tag'),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON condition for matching messages'),
    sa.Column('description', sa.Text(), nullable=True, comment='Tag description'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether tag is currently active'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_tag_type'), 'tags', ['tag_type'], unique=False)
    op.create_table('channels',
    sa.Column('telegram_id', sa.String(length=255), nullable=False, comment='Unique Telegram channel ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Channel name'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Channel username without @'),
    sa.Column('category_id', sa.UUID(), nullable=True, comment='Foreign key to category'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether channel is currently being monitored'),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True, comment='Last time channel was synced'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_category_id'), 'channels', ['category_id'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_telegram_id'), 'channels', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=False)
    op.create_table('messages',
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False, comment='Original Telegram message ID'),
    sa.Column('channel_id', sa.UUID(), nullable=False, comment='Foreign key to channel'),
    sa.Column('text', sa.Text(), nullable=True, comment='Original message text'),
    sa.Column('text_normalized', sa.Text(), nullable=True, comment='Normalized message text (processed with hazm)'),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='Message publish date'),
    sa.Column('views', sa.Integer(), nullable=True, comment='Number of views'),
    sa.Column('forwards', sa.Integer(), nullable=True, comment='Number of forwards'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional metadata as JSON'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_date', 'messages', ['channel_id', 'date'], unique=False)
    op.create_index('idx_channel_telegram_id', 'messages', ['channel_id', 'telegram_message_id'], unique=True)
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_date'), 'messages', ['date'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('message_tags',
    sa.Column('message_id', sa.UUID(), nullable=False, comment='Foreign key to message'),
    sa.Column('tag_id', sa.UUID(), nullable=False, comment='Foreign key to tag'),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when tag was matched'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'tag_id'),
    sa.UniqueConstraint('message_id', 'tag_id', name='uq_message_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_tags')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_date'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_index('idx_channel_telegram_id', table_name='messages')
    op.drop_index('idx_channel_date', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.drop_index(op.f('ix_channels_telegram_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_category_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_tags_tag_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
