"""Add extra_data field to dictionary_words

Revision ID: 74d7c0b1a1f0
Revises: 2e171cde7221
Create Date: 2025-11-15 16:03:14.763501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74d7c0b1a1f0'
down_revision: Union[str, None] = '2e171cde7221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dictionary_words', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data (e.g., symbol_name, company_name, industry_name)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dictionary_words', 'extra_data')
    # ### end Alembic commands ###
