"""add_time_slot_and_jalali_date_to_channel_analytics

Revision ID: 129d6cc04084
Revises: 0b30f7c5b26a
Create Date: 2025-11-16 18:11:49.374287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129d6cc04084'
down_revision: Union[str, None] = '0b30f7c5b26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_analytics', sa.Column('time_slot', sa.Integer(), nullable=True, comment='5-minute time slot within hour (0-11), NULL for hourly/daily aggregates'))
    op.add_column('channel_analytics', sa.Column('jalali_date', sa.String(length=20), nullable=True, comment="Jalali date string (e.g., '1404-08-25')"))
    op.drop_constraint(op.f('uq_channel_date_hour'), 'channel_analytics', type_='unique')
    op.create_unique_constraint('uq_channel_date_hour_slot', 'channel_analytics', ['channel_id', 'date', 'hour', 'time_slot'])
    # Skip creating uq_message_tag - it already exists
    # op.create_unique_constraint('uq_message_tag', 'message_tags', ['message_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping uq_message_tag - we didn't create it
    # op.drop_constraint('uq_message_tag', 'message_tags', type_='unique')
    op.drop_constraint('uq_channel_date_hour_slot', 'channel_analytics', type_='unique')
    op.create_unique_constraint(op.f('uq_channel_date_hour'), 'channel_analytics', ['channel_id', 'date', 'hour'], postgresql_nulls_not_distinct=False)
    op.drop_column('channel_analytics', 'jalali_date')
    op.drop_column('channel_analytics', 'time_slot')
    # ### end Alembic commands ###
